#include <bits/stdc++.h>

using namespace std;

int main()
{
    int n;
    scanf("%d", &n);
    if(n==1) printf("Bulbasaur\nGrass Poison");
    else if(n==2) printf("Ivysaur\nGrass Poison");
    else if(n==3) printf("Venusaur\nGrass Poison");
    else if(n==4) printf("Charmander\nFire");
    else if(n==5) printf("Charmeleon\nFire");
    else if(n==6) printf("Charizard\nFire Flying");
    else if(n==7) printf("Squirtle\nWater");
    else if(n==8) printf("Wartortle\nWater");
    else if(n==9) printf("Blastoise\nWater");
    else if(n==10) printf("Caterpie\nBug");
    else if(n==11) printf("Metapod\nBug");
    else if(n==12) printf("Butterfree\nBug Flying");
    else if(n==13) printf("Weedle\nBug Poison");
    else if(n==14) printf("Kakuna\nBug Poison");
    else if(n==15) printf("Beedrill\nBug Poison");
    else if(n==16) printf("Pidgey\nNormal Flying");
    else if(n==17) printf("Pidgeotto\nNormal Flying");
    else if(n==18) printf("Pidgeot\nNormal Flying");
    else if(n==19) printf("Rattata\nNormal");
    else if(n==20) printf("Raticate\nNormal");
    else if(n==21) printf("Spearow\nNormal Flying");
    else if(n==22) printf("Fearow\nNormal Flying");
    else if(n==23) printf("Ekans\nPoison");
    else if(n==24) printf("Arbok\nPoison");
    else if(n==25) printf("Pikachu\nElectric");
    else if(n==26) printf("Raichu\nElectric");
    else if(n==27) printf("Sandshrew\nGround");
    else if(n==28) printf("Sandslash\nGround");
    else if(n==29) printf("Nidoran♀\nPoison");
    else if(n==30) printf("Nidorina\nPoison");
    else if(n==31) printf("Nidoqueen\nPoison Ground");
    else if(n==32) printf("Nidoran♂\nPoison");
    else if(n==33) printf("Nidorino\nPoison");
    else if(n==34) printf("Nidoking\nPoison Ground");
    else if(n==35) printf("Clefairy\nFairy");
    else if(n==36) printf("Clefable\nFairy");
    else if(n==37) printf("Vulpix\nFire");
    else if(n==38) printf("Ninetales\nFire");
    else if(n==39) printf("Jigglypuff\nNormal Fairy");
    else if(n==40) printf("Wigglytuff\nNormal Fairy");
    else if(n==41) printf("Zubat\nPoison Flying");
    else if(n==42) printf("Golbat\nPoison Flying");
    else if(n==43) printf("Oddish\nGrass Poison");
    else if(n==44) printf("Gloom\nGrass Poison");
    else if(n==45) printf("Vileplume\nGrass Poison");
    else if(n==46) printf("Paras\nBug Grass");
    else if(n==47) printf("Parasect\nBug Grass");
    else if(n==48) printf("Venonat\nBug Poison");
    else if(n==49) printf("Venomoth\nBug Poison");
    else if(n==50) printf("Diglett\nGround");
    else if(n==51) printf("Dugtrio\nGround");
    else if(n==52) printf("Meowth\nNormal");
    else if(n==53) printf("Persian\nNormal");
    else if(n==54) printf("Psyduck\nWater");
    else if(n==55) printf("Golduck\nWater");
    else if(n==56) printf("Mankey\nFighting");
    else if(n==57) printf("Primeape\nFighting");
    else if(n==58) printf("Growlithe\nFire");
    else if(n==59) printf("Arcanine\nFire");
    else if(n==60) printf("Poliwag\nWater");
    else if(n==61) printf("Poliwhirl\nWater");
    else if(n==62) printf("Poliwrath\nWater Fighting");
    else if(n==63) printf("Abra\nPsychic");
    else if(n==64) printf("Kadabra\nPsychic");
    else if(n==65) printf("Alakazam\nPsychic");
    else if(n==66) printf("Machop\nFighting");
    else if(n==67) printf("Machoke\nFighting");
    else if(n==68) printf("Machamp\nFighting");
    else if(n==69) printf("Bellsprout\nGrass Poison");
    else if(n==70) printf("Weepinbell\nGrass Poison");
    else if(n==71) printf("Victreebel\nGrass Poison");
    else if(n==72) printf("Tentacool\nWater Poison");
    else if(n==73) printf("Tentacruel\nWater Poison");
    else if(n==74) printf("Geodude\nRock Ground");
    else if(n==75) printf("Graveler\nRock Ground");
    else if(n==76) printf("Golem\nRock Ground");
    else if(n==77) printf("Ponyta\nFire");
    else if(n==78) printf("Rapidash\nFire");
    else if(n==79) printf("Slowpoke\nWater Psychic");
    else if(n==80) printf("Slowbro\nWater Psychic");
    else if(n==81) printf("Magnemite\nElectric Steel");
    else if(n==82) printf("Magneton\nElectric Steel");
    else if(n==83) printf("Farfetch'd\nNormal Flying");
    else if(n==84) printf("Doduo\nNormal Flying");
    else if(n==85) printf("Dodrio\nNormal Flying");
    else if(n==86) printf("Seel\nWater");
    else if(n==87) printf("Dewgong\nWater Ice");
    else if(n==88) printf("Grimer\nPoison");
    else if(n==89) printf("Muk\nPoison");
    else if(n==90) printf("Shellder\nWater");
    else if(n==91) printf("Cloyster\nWater Ice");
    else if(n==92) printf("Gastly\nGhost Poison");
    else if(n==93) printf("Haunter\nGhost Poison");
    else if(n==94) printf("Gengar\nGhost Poison");
    else if(n==95) printf("Onix\nRock Ground");
    else if(n==96) printf("Drowzee\nPsychic");
    else if(n==97) printf("Hypno\nPsychic");
    else if(n==98) printf("Krabby\nWater");
    else if(n==99) printf("Kingler\nWater");
    else if(n==100) printf("Voltorb\nElectric");
    else if(n==101) printf("Electrode\nElectric");
    else if(n==102) printf("Exeggcute\nGrass Psychic");
    else if(n==103) printf("Exeggutor\nGrass Psychic");
    else if(n==104) printf("Cubone\nGround");
    else if(n==105) printf("Marowak\nGround");
    else if(n==106) printf("Hitmonlee\nFighting");
    else if(n==107) printf("Hitmonchan\nFighting");
    else if(n==108) printf("Lickitung\nNormal");
    else if(n==109) printf("Koffing\nPoison");
    else if(n==110) printf("Weezing\nPoison");
    else if(n==111) printf("Rhyhorn\nGround Rock");
    else if(n==112) printf("Rhydon\nGround Rock");
    else if(n==113) printf("Chansey\nNormal");
    else if(n==114) printf("Tangela\nGrass");
    else if(n==115) printf("Kangaskhan\nNormal");
    else if(n==116) printf("Horsea\nWater");
    else if(n==117) printf("Seadra\nWater");
    else if(n==118) printf("Goldeen\nWater");
    else if(n==119) printf("Seaking\nWater");
    else if(n==120) printf("Staryu\nWater");
    else if(n==121) printf("Starmie\nWater Psychic");
    else if(n==122) printf("Mr. Mime\nPsychic Fairy");
    else if(n==123) printf("Scyther\nBug Flying");
    else if(n==124) printf("Jynx\nIce Psychic");
    else if(n==125) printf("Electabuzz\nElectric");
    else if(n==126) printf("Magmar\nFire");
    else if(n==127) printf("Pinsir\nBug");
    else if(n==128) printf("Tauros\nNormal");
    else if(n==129) printf("Magikarp\nWater");
    else if(n==130) printf("Gyarados\nWater Flying");
    else if(n==131) printf("Lapras\nWater Ice");
    else if(n==132) printf("Ditto\nNormal");
    else if(n==133) printf("Eevee\nNormal");
    else if(n==134) printf("Vaporeon\nWater");
    else if(n==135) printf("Jolteon\nElectric");
    else if(n==136) printf("Flareon\nFire");
    else if(n==137) printf("Porygon\nNormal");
    else if(n==138) printf("Omanyte\nRock Water");
    else if(n==139) printf("Omastar\nRock Water");
    else if(n==140) printf("Kabuto\nRock Water");
    else if(n==141) printf("Kabutops\nRock Water");
    else if(n==142) printf("Aerodactyl\nRock Flying");
    else if(n==143) printf("Snorlax\nNormal");
    else if(n==144) printf("Articuno\nIce Flying");
    else if(n==145) printf("Zapdos\nElectric Flying");
    else if(n==146) printf("Moltres\nFire Flying");
    else if(n==147) printf("Dratini\nDragon");
    else if(n==148) printf("Dragonair\nDragon");
    else if(n==149) printf("Dragonite\nDragon Flying");
    else if(n==150) printf("Mewtwo\nPsychic");
    else if(n==151) printf("Mew\nPsychic");
    else if(n==152) printf("Chikorita\nGrass");
    else if(n==153) printf("Bayleef\nGrass");
    else if(n==154) printf("Meganium\nGrass");
    else if(n==155) printf("Cyndaquil\nFire");
    else if(n==156) printf("Quilava\nFire");
    else if(n==157) printf("Typhlosion\nFire");
    else if(n==158) printf("Totodile\nWater");
    else if(n==159) printf("Croconaw\nWater");
    else if(n==160) printf("Feraligatr\nWater");
    else if(n==161) printf("Sentret\nNormal");
    else if(n==162) printf("Furret\nNormal");
    else if(n==163) printf("Hoothoot\nNormal Flying");
    else if(n==164) printf("Noctowl\nNormal Flying");
    else if(n==165) printf("Ledyba\nBug Flying");
    else if(n==166) printf("Ledian\nBug Flying");
    else if(n==167) printf("Spinarak\nBug Poison");
    else if(n==168) printf("Ariados\nBug Poison");
    else if(n==169) printf("Crobat\nPoison Flying");
    else if(n==170) printf("Chinchou\nWater Electric");
    else if(n==171) printf("Lanturn\nWater Electric");
    else if(n==172) printf("Pichu\nElectric");
    else if(n==173) printf("Cleffa\nFairy");
    else if(n==174) printf("Igglybuff\nNormal Fairy");
    else if(n==175) printf("Togepi\nFairy");
    else if(n==176) printf("Togetic\nFairy Flying");
    else if(n==177) printf("Natu\nPsychic Flying");
    else if(n==178) printf("Xatu\nPsychic Flying");
    else if(n==179) printf("Mareep\nElectric");
    else if(n==180) printf("Flaaffy\nElectric");
    else if(n==181) printf("Ampharos\nElectric");
    else if(n==182) printf("Bellossom\nGrass");
    else if(n==183) printf("Marill\nWater Fairy");
    else if(n==184) printf("Azumarill\nWater Fairy");
    else if(n==185) printf("Sudowoodo\nRock");
    else if(n==186) printf("Politoed\nWater");
    else if(n==187) printf("Hoppip\nGrass Flying");
    else if(n==188) printf("Skiploom\nGrass Flying");
    else if(n==189) printf("Jumpluff\nGrass Flying");
    else if(n==190) printf("Aipom\nNormal");
    else if(n==191) printf("Sunkern\nGrass");
    else if(n==192) printf("Sunflora\nGrass");
    else if(n==193) printf("Yanma\nBug Flying");
    else if(n==194) printf("Wooper\nWater Ground");
    else if(n==195) printf("Quagsire\nWater Ground");
    else if(n==196) printf("Espeon\nPsychic");
    else if(n==197) printf("Umbreon\nDark");
    else if(n==198) printf("Murkrow\nDark Flying");
    else if(n==199) printf("Slowking\nWater Psychic");
    else if(n==200) printf("Misdreavus\nGhost");
    else if(n==201) printf("Unown\nPsychic");
    else if(n==202) printf("Wobbuffet\nPsychic");
    else if(n==203) printf("Girafarig\nNormal Psychic");
    else if(n==204) printf("Pineco\nBug");
    else if(n==205) printf("Forretress\nBug Steel");
    else if(n==206) printf("Dunsparce\nNormal");
    else if(n==207) printf("Gligar\nGround Flying");
    else if(n==208) printf("Steelix\nSteel Ground");
    else if(n==209) printf("Snubbull\nFairy");
    else if(n==210) printf("Granbull\nFairy");
    else if(n==211) printf("Qwilfish\nWater Poison");
    else if(n==212) printf("Scizor\nBug Steel");
    else if(n==213) printf("Shuckle\nBug Rock");
    else if(n==214) printf("Heracross\nBug Fighting");
    else if(n==215) printf("Sneasel\nDark Ice");
    else if(n==216) printf("Teddiursa\nNormal");
    else if(n==217) printf("Ursaring\nNormal");
    else if(n==218) printf("Slugma\nFire");
    else if(n==219) printf("Magcargo\nFire Rock");
    else if(n==220) printf("Swinub\nIce Ground");
    else if(n==221) printf("Piloswine\nIce Ground");
    else if(n==222) printf("Corsola\nWater Rock");
    else if(n==223) printf("Remoraid\nWater");
    else if(n==224) printf("Octillery\nWater");
    else if(n==225) printf("Delibird\nIce Flying");
    else if(n==226) printf("Mantine\nWater Flying");
    else if(n==227) printf("Skarmory\nSteel Flying");
    else if(n==228) printf("Houndour\nDark Fire");
    else if(n==229) printf("Houndoom\nDark Fire");
    else if(n==230) printf("Kingdra\nWater Dragon");
    else if(n==231) printf("Phanpy\nGround");
    else if(n==232) printf("Donphan\nGround");
    else if(n==233) printf("Porygon2\nNormal");
    else if(n==234) printf("Stantler\nNormal");
    else if(n==235) printf("Smeargle\nNormal");
    else if(n==236) printf("Tyrogue\nFighting");
    else if(n==237) printf("Hitmontop\nFighting");
    else if(n==238) printf("Smoochum\nIce Psychic");
    else if(n==239) printf("Elekid\nElectric");
    else if(n==240) printf("Magby\nFire");
    else if(n==241) printf("Miltank\nNormal");
    else if(n==242) printf("Blissey\nNormal");
    else if(n==243) printf("Raikou\nElectric");
    else if(n==244) printf("Entei\nFire");
    else if(n==245) printf("Suicune\nWater");
    else if(n==246) printf("Larvitar\nRock Ground");
    else if(n==247) printf("Pupitar\nRock Ground");
    else if(n==248) printf("Tyranitar\nRock Dark");
    else if(n==249) printf("Lugia\nPsychic Flying");
    else if(n==250) printf("Ho-oh\nFire Flying");
    else if(n==251) printf("Celebi\nPsychic Grass");
    else if(n==252) printf("Treecko\nGrass");
    else if(n==253) printf("Grovyle\nGrass");
    else if(n==254) printf("Sceptile\nGrass");
    else if(n==255) printf("Torchic\nFire");
    else if(n==256) printf("Combusken\nFire Fighting");
    else if(n==257) printf("Blaziken\nFire Fighting");
    else if(n==258) printf("Mudkip\nWater");
    else if(n==259) printf("Marshtomp\nWater Ground");
    else if(n==260) printf("Swampert\nWater Ground");
    else if(n==261) printf("Poochyena\nDark");
    else if(n==262) printf("Mightyena\nDark");
    else if(n==263) printf("Zigzagoon\nNormal");
    else if(n==264) printf("Linoone\nNormal");
    else if(n==265) printf("Wurmple\nBug");
    else if(n==266) printf("Silcoon\nBug");
    else if(n==267) printf("Beautifly\nBug Flying");
    else if(n==268) printf("Cascoon\nBug");
    else if(n==269) printf("Dustox\nBug Poison");
    else if(n==270) printf("Lotad\nWater Grass");
    else if(n==271) printf("Lombre\nWater Grass");
    else if(n==272) printf("Ludicolo\nWater Grass");
    else if(n==273) printf("Seedot\nGrass");
    else if(n==274) printf("Nuzleaf\nGrass Dark");
    else if(n==275) printf("Shiftry\nGrass Dark");
    else if(n==276) printf("Taillow\nNormal Flying");
    else if(n==277) printf("Swellow\nNormal Flying");
    else if(n==278) printf("Wingull\nWater Flying");
    else if(n==279) printf("Pelipper\nWater Flying");
    else if(n==280) printf("Ralts\nPsychic Fairy");
    else if(n==281) printf("Kirlia\nPsychic Fairy");
    else if(n==282) printf("Gardevoir\nPsychic Fairy");
    else if(n==283) printf("Surskit\nBug Water");
    else if(n==284) printf("Masquerain\nBug Flying");
    else if(n==285) printf("Shroomish\nGrass");
    else if(n==286) printf("Breloom\nGrass Fighting");
    else if(n==287) printf("Slakoth\nNormal");
    else if(n==288) printf("Vigoroth\nNormal");
    else if(n==289) printf("Slaking\nNormal");
    else if(n==290) printf("Nincada\nBug Ground");
    else if(n==291) printf("Ninjask\nBug Flying");
    else if(n==292) printf("Shedinja\nBug Ghost");
    else if(n==293) printf("Whismur\nNormal");
    else if(n==294) printf("Loudred\nNormal");
    else if(n==295) printf("Exploud\nNormal");
    else if(n==296) printf("Makuhita\nFighting");
    else if(n==297) printf("Hariyama\nFighting");
    else if(n==298) printf("Azurill\nNormal Fairy");
    else if(n==299) printf("Nosepass\nRock");
    else if(n==300) printf("Skitty\nNormal");
    else if(n==301) printf("Delcatty\nNormal");
    else if(n==302) printf("Sableye\nDark Ghost");
    else if(n==303) printf("Mawile\nSteel Fairy");
    else if(n==304) printf("Aron\nSteel Rock");
    else if(n==305) printf("Lairon\nSteel Rock");
    else if(n==306) printf("Aggron\nSteel Rock");
    else if(n==307) printf("Meditite\nFighting Psychic");
    else if(n==308) printf("Medicham\nFighting Psychic");
    else if(n==309) printf("Electrike\nElectric");
    else if(n==310) printf("Manectric\nElectric");
    else if(n==311) printf("Plusle\nElectric");
    else if(n==312) printf("Minun\nElectric");
    else if(n==313) printf("Volbeat\nBug");
    else if(n==314) printf("Illumise\nBug");
    else if(n==315) printf("Roselia\nGrass Poison");
    else if(n==316) printf("Gulpin\nPoison");
    else if(n==317) printf("Swalot\nPoison");
    else if(n==318) printf("Carvanha\nWater Dark");
    else if(n==319) printf("Sharpedo\nWater Dark");
    else if(n==320) printf("Wailmer\nWater");
    else if(n==321) printf("Wailord\nWater");
    else if(n==322) printf("Numel\nFire Ground");
    else if(n==323) printf("Camerupt\nFire Ground");
    else if(n==324) printf("Torkoal\nFire");
    else if(n==325) printf("Spoink\nPsychic");
    else if(n==326) printf("Grumpig\nPsychic");
    else if(n==327) printf("Spinda\nNormal");
    else if(n==328) printf("Trapinch\nGround");
    else if(n==329) printf("Vibrava\nGround Dragon");
    else if(n==330) printf("Flygon\nGround Dragon");
    else if(n==331) printf("Cacnea\nGrass");
    else if(n==332) printf("Cacturne\nGrass Dark");
    else if(n==333) printf("Swablu\nNormal Flying");
    else if(n==334) printf("Altaria\nDragon Flying");
    else if(n==335) printf("Zangoose\nNormal");
    else if(n==336) printf("Seviper\nPoison");
    else if(n==337) printf("Lunatone\nRock Psychic");
    else if(n==338) printf("Solrock\nRock Psychic");
    else if(n==339) printf("Barboach\nWater Ground");
    else if(n==340) printf("Whiscash\nWater Ground");
    else if(n==341) printf("Corphish\nWater");
    else if(n==342) printf("Crawdaunt\nWater Dark");
    else if(n==343) printf("Baltoy\nGround Psychic");
    else if(n==344) printf("Claydol\nGround Psychic");
    else if(n==345) printf("Lileep\nRock Grass");
    else if(n==346) printf("Cradily\nRock Grass");
    else if(n==347) printf("Anorith\nRock Bug");
    else if(n==348) printf("Armaldo\nRock Bug");
    else if(n==349) printf("Feebas\nWater");
    else if(n==350) printf("Milotic\nWater");
    else if(n==351) printf("Castform\nNormal");
    else if(n==352) printf("Kecleon\nNormal");
    else if(n==353) printf("Shuppet\nGhost");
    else if(n==354) printf("Banette\nGhost");
    else if(n==355) printf("Duskull\nGhost");
    else if(n==356) printf("Dusclops\nGhost");
    else if(n==357) printf("Tropius\nGrass Flying");
    else if(n==358) printf("Chimecho\nPsychic");
    else if(n==359) printf("Absol\nDark");
    else if(n==360) printf("Wynaut\nPsychic");
    else if(n==361) printf("Snorunt\nIce");
    else if(n==362) printf("Glalie\nIce");
    else if(n==363) printf("Spheal\nIce Water");
    else if(n==364) printf("Sealeo\nIce Water");
    else if(n==365) printf("Walrein\nIce Water");
    else if(n==366) printf("Clamperl\nWater");
    else if(n==367) printf("Huntail\nWater");
    else if(n==368) printf("Gorebyss\nWater");
    else if(n==369) printf("Relicanth\nWater Rock");
    else if(n==370) printf("Luvdisc\nWater");
    else if(n==371) printf("Bagon\nDragon");
    else if(n==372) printf("Shelgon\nDragon");
    else if(n==373) printf("Salamence\nDragon Flying");
    else if(n==374) printf("Beldum\nSteel Psychic");
    else if(n==375) printf("Metang\nSteel Psychic");
    else if(n==376) printf("Metagross\nSteel Psychic");
    else if(n==377) printf("Regirock\nRock");
    else if(n==378) printf("Regice\nIce");
    else if(n==379) printf("Registeel\nSteel");
    else if(n==380) printf("Latias\nDragon Psychic");
    else if(n==381) printf("Latios\nDragon Psychic");
    else if(n==382) printf("Kyogre\nWater");
    else if(n==383) printf("Groudon\nGround");
    else if(n==384) printf("Rayquaza\nDragon Flying");
    else if(n==385) printf("Jirachi\nSteel Psychic");
    else if(n==386) printf("Deoxys\nPsychic");
    else if(n==387) printf("Turtwig\nGrass");
    else if(n==388) printf("Grotle\nGrass");
    else if(n==389) printf("Torterra\nGrass Ground");
    else if(n==390) printf("Chimchar\nFire");
    else if(n==391) printf("Monferno\nFire Fighting");
    else if(n==392) printf("Infernape\nFire Fighting");
    else if(n==393) printf("Piplup\nWater");
    else if(n==394) printf("Prinplup\nWater");
    else if(n==395) printf("Empoleon\nWater Steel");
    else if(n==396) printf("Starly\nNormal Flying");
    else if(n==397) printf("Staravia\nNormal Flying");
    else if(n==398) printf("Staraptor\nNormal Flying");
    else if(n==399) printf("Bidoof\nNormal");
    else if(n==400) printf("Bibarel\nNormal Water");
    else if(n==401) printf("Kricketot\nBug");
    else if(n==402) printf("Kricketune\nBug");
    else if(n==403) printf("Shinx\nElectric");
    else if(n==404) printf("Luxio\nElectric");
    else if(n==405) printf("Luxray\nElectric");
    else if(n==406) printf("Budew\nGrass Poison");
    else if(n==407) printf("Roserade\nGrass Poison");
    else if(n==408) printf("Cranidos\nRock");
    else if(n==409) printf("Rampardos\nRock");
    else if(n==410) printf("Shieldon\nRock Steel");
    else if(n==411) printf("Bastiodon\nRock Steel");
    else if(n==412) printf("Burmy\nBug");
    else if(n==413) printf("Wormadam\nBug Grass");
    else if(n==414) printf("Mothim\nBug Flying");
    else if(n==415) printf("Combee\nBug Flying");
    else if(n==416) printf("Vespiquen\nBug Flying");
    else if(n==417) printf("Pachirisu\nElectric");
    else if(n==418) printf("Buizel\nWater");
    else if(n==419) printf("Floatzel\nWater");
    else if(n==420) printf("Cherubi\nGrass");
    else if(n==421) printf("Cherrim\nGrass");
    else if(n==422) printf("Shellos\nWater");
    else if(n==423) printf("Gastrodon\nWater Ground");
    else if(n==424) printf("Ambipom\nNormal");
    else if(n==425) printf("Drifloon\nGhost Flying");
    else if(n==426) printf("Drifblim\nGhost Flying");
    else if(n==427) printf("Buneary\nNormal");
    else if(n==428) printf("Lopunny\nNormal");
    else if(n==429) printf("Mismagius\nGhost");
    else if(n==430) printf("Honchkrow\nDark Flying");
    else if(n==431) printf("Glameow\nNormal");
    else if(n==432) printf("Purugly\nNormal");
    else if(n==433) printf("Chingling\nPsychic");
    else if(n==434) printf("Stunky\nPoison Dark");
    else if(n==435) printf("Skuntank\nPoison Dark");
    else if(n==436) printf("Bronzor\nSteel Psychic");
    else if(n==437) printf("Bronzong\nSteel Psychic");
    else if(n==438) printf("Bonsly\nRock");
    else if(n==439) printf("Mime Jr.\nPsychic Fairy");
    else if(n==440) printf("Happiny\nNormal");
    else if(n==441) printf("Chatot\nNormal Flying");
    else if(n==442) printf("Spiritomb\nGhost Dark");
    else if(n==443) printf("Gible\nDragon Ground");
    else if(n==444) printf("Gabite\nDragon Ground");
    else if(n==445) printf("Garchomp\nDragon Ground");
    else if(n==446) printf("Munchlax\nNormal");
    else if(n==447) printf("Riolu\nFighting");
    else if(n==448) printf("Lucario\nFighting Steel");
    else if(n==449) printf("Hippopotas\nGround");
    else if(n==450) printf("Hippowdon\nGround");
    else if(n==451) printf("Skorupi\nPoison Bug");
    else if(n==452) printf("Drapion\nPoison Dark");
    else if(n==453) printf("Croagunk\nPoison Fighting");
    else if(n==454) printf("Toxicroak\nPoison Fighting");
    else if(n==455) printf("Carnivine\nGrass");
    else if(n==456) printf("Finneon\nWater");
    else if(n==457) printf("Lumineon\nWater");
    else if(n==458) printf("Mantyke\nWater Flying");
    else if(n==459) printf("Snover\nGrass Ice");
    else if(n==460) printf("Abomasnow\nGrass Ice");
    else if(n==461) printf("Weavile\nDark Ice");
    else if(n==462) printf("Magnezone\nElectric Steel");
    else if(n==463) printf("Lickilicky\nNormal");
    else if(n==464) printf("Rhyperior\nGround Rock");
    else if(n==465) printf("Tangrowth\nGrass");
    else if(n==466) printf("Electivire\nElectric");
    else if(n==467) printf("Magmortar\nFire");
    else if(n==468) printf("Togekiss\nFairy Flying");
    else if(n==469) printf("Yanmega\nBug Flying");
    else if(n==470) printf("Leafeon\nGrass");
    else if(n==471) printf("Glaceon\nIce");
    else if(n==472) printf("Gliscor\nGround Flying");
    else if(n==473) printf("Mamoswine\nIce Ground");
    else if(n==474) printf("Porygon-Z\nNormal");
    else if(n==475) printf("Gallade\nPsychic Fighting");
    else if(n==476) printf("Probopass\nRock Steel");
    else if(n==477) printf("Dusknoir\nGhost");
    else if(n==478) printf("Froslass\nIce Ghost");
    else if(n==479) printf("Rotom\nElectric Ghost");
    else if(n==480) printf("Uxie\nPsychic");
    else if(n==481) printf("Mesprit\nPsychic");
    else if(n==482) printf("Azelf\nPsychic");
    else if(n==483) printf("Dialga\nSteel Dragon");
    else if(n==484) printf("Palkia\nWater Dragon");
    else if(n==485) printf("Heatran\nFire Steel");
    else if(n==486) printf("Regigigas\nNormal");
    else if(n==487) printf("Giratina\nGhost Dragon");
    else if(n==488) printf("Cresselia\nPsychic");
    else if(n==489) printf("Phione\nWater");
    else if(n==490) printf("Manaphy\nWater");
    else if(n==491) printf("Darkrai\nDark");
    else if(n==492) printf("Shaymin\nGrass");
    else if(n==493) printf("Arceus\nNormal");
    else if(n==494) printf("Victini\nPsychic Fire");
    else if(n==495) printf("Snivy\nGrass");
    else if(n==496) printf("Servine\nGrass");
    else if(n==497) printf("Serperior\nGrass");
    else if(n==498) printf("Tepig\nFire");
    else if(n==499) printf("Pignite\nFire Fighting");
    else if(n==500) printf("Emboar\nFire Fighting");
    else if(n==501) printf("Oshawott\nWater");
    else if(n==502) printf("Dewott\nWater");
    else if(n==503) printf("Samurott\nWater");
    else if(n==504) printf("Patrat\nNormal");
    else if(n==505) printf("Watchog\nNormal");
    else if(n==506) printf("Lillipup\nNormal");
    else if(n==507) printf("Herdier\nNormal");
    else if(n==508) printf("Stoutland\nNormal");
    else if(n==509) printf("Purrloin\nDark");
    else if(n==510) printf("Liepard\nDark");
    else if(n==511) printf("Pansage\nGrass");
    else if(n==512) printf("Simisage\nGrass");
    else if(n==513) printf("Pansear\nFire");
    else if(n==514) printf("Simisear\nFire");
    else if(n==515) printf("Panpour\nWater");
    else if(n==516) printf("Simipour\nWater");
    else if(n==517) printf("Munna\nPsychic");
    else if(n==518) printf("Musharna\nPsychic");
    else if(n==519) printf("Pidove\nNormal Flying");
    else if(n==520) printf("Tranquill\nNormal Flying");
    else if(n==521) printf("Unfezant\nNormal Flying");
    else if(n==522) printf("Blitzle\nElectric");
    else if(n==523) printf("Zebstrika\nElectric");
    else if(n==524) printf("Roggenrola\nRock");
    else if(n==525) printf("Boldore\nRock");
    else if(n==526) printf("Gigalith\nRock");
    else if(n==527) printf("Woobat\nPsychic Flying");
    else if(n==528) printf("Swoobat\nPsychic Flying");
    else if(n==529) printf("Drilbur\nGround");
    else if(n==530) printf("Excadrill\nGround Steel");
    else if(n==531) printf("Audino\nNormal");
    else if(n==532) printf("Timburr\nFighting");
    else if(n==533) printf("Gurdurr\nFighting");
    else if(n==534) printf("Conkeldurr\nFighting");
    else if(n==535) printf("Tympole\nWater");
    else if(n==536) printf("Palpitoad\nWater Ground");
    else if(n==537) printf("Seismitoad\nWater Ground");
    else if(n==538) printf("Throh\nFighting");
    else if(n==539) printf("Sawk\nFighting");
    else if(n==540) printf("Sewaddle\nBug Grass");
    else if(n==541) printf("Swadloon\nBug Grass");
    else if(n==542) printf("Leavanny\nBug Grass");
    else if(n==543) printf("Venipede\nBug Poison");
    else if(n==544) printf("Whirlipede\nBug Poison");
    else if(n==545) printf("Scolipede\nBug Poison");
    else if(n==546) printf("Cottonee\nGrass Fairy");
    else if(n==547) printf("Whimsicott\nGrass Fairy");
    else if(n==548) printf("Petilil\nGrass");
    else if(n==549) printf("Lilligant\nGrass");
    else if(n==550) printf("Basculin\nWater");
    else if(n==551) printf("Sandile\nGround Dark");
    else if(n==552) printf("Krokorok\nGround Dark");
    else if(n==553) printf("Krookodile\nGround Dark");
    else if(n==554) printf("Darumaka\nFire");
    else if(n==555) printf("Darmanitan\nFire");
    else if(n==556) printf("Maractus\nGrass");
    else if(n==557) printf("Dwebble\nBug Rock");
    else if(n==558) printf("Crustle\nBug Rock");
    else if(n==559) printf("Scraggy\nDark Fighting");
    else if(n==560) printf("Scrafty\nDark Fighting");
    else if(n==561) printf("Sigilyph\nPsychic Flying");
    else if(n==562) printf("Yamask\nGhost");
    else if(n==563) printf("Cofagrigus\nGhost");
    else if(n==564) printf("Tirtouga\nWater Rock");
    else if(n==565) printf("Carracosta\nWater Rock");
    else if(n==566) printf("Archen\nRock Flying");
    else if(n==567) printf("Archeops\nRock Flying");
    else if(n==568) printf("Trubbish\nPoison");
    else if(n==569) printf("Garbodor\nPoison");
    else if(n==570) printf("Zorua\nDark");
    else if(n==571) printf("Zoroark\nDark");
    else if(n==572) printf("Minccino\nNormal");
    else if(n==573) printf("Cinccino\nNormal");
    else if(n==574) printf("Gothita\nPsychic");
    else if(n==575) printf("Gothorita\nPsychic");
    else if(n==576) printf("Gothitelle\nPsychic");
    else if(n==577) printf("Solosis\nPsychic");
    else if(n==578) printf("Duosion\nPsychic");
    else if(n==579) printf("Reuniclus\nPsychic");
    else if(n==580) printf("Ducklett\nWater Flying");
    else if(n==581) printf("Swanna\nWater Flying");
    else if(n==582) printf("Vanillite\nIce");
    else if(n==583) printf("Vanillish\nIce");
    else if(n==584) printf("Vanilluxe\nIce");
    else if(n==585) printf("Deerling\nNormal Grass");
    else if(n==586) printf("Sawsbuck\nNormal Grass");
    else if(n==587) printf("Emolga\nElectric Flying");
    else if(n==588) printf("Karrablast\nBug");
    else if(n==589) printf("Escavalier\nBug Steel");
    else if(n==590) printf("Foongus\nGrass Poison");
    else if(n==591) printf("Amoonguss\nGrass Poison");
    else if(n==592) printf("Frillish\nWater Ghost");
    else if(n==593) printf("Jellicent\nWater Ghost");
    else if(n==594) printf("Alomomola\nWater");
    else if(n==595) printf("Joltik\nBug Electric");
    else if(n==596) printf("Galvantula\nBug Electric");
    else if(n==597) printf("Ferroseed\nGrass Steel");
    else if(n==598) printf("Ferrothorn\nGrass Steel");
    else if(n==599) printf("Klink\nSteel");
    else if(n==600) printf("Klang\nSteel");
    else if(n==601) printf("Klinklang\nSteel");
    else if(n==602) printf("Tynamo\nElectric");
    else if(n==603) printf("Eelektrik\nElectric");
    else if(n==604) printf("Eelektross\nElectric");
    else if(n==605) printf("Elgyem\nPsychic");
    else if(n==606) printf("Beheeyem\nPsychic");
    else if(n==607) printf("Litwick\nGhost Fire");
    else if(n==608) printf("Lampent\nGhost Fire");
    else if(n==609) printf("Chandelure\nGhost Fire");
    else if(n==610) printf("Axew\nDragon");
    else if(n==611) printf("Fraxure\nDragon");
    else if(n==612) printf("Haxorus\nDragon");
    else if(n==613) printf("Cubchoo\nIce");
    else if(n==614) printf("Beartic\nIce");
    else if(n==615) printf("Cryogonal\nIce");
    else if(n==616) printf("Shelmet\nBug");
    else if(n==617) printf("Accelgor\nBug");
    else if(n==618) printf("Stunfisk\nElectric Ground");
    else if(n==619) printf("Mienfoo\nFighting");
    else if(n==620) printf("Mienshao\nFighting");
    else if(n==621) printf("Druddigon\nDragon");
    else if(n==622) printf("Golett\nGround Ghost");
    else if(n==623) printf("Golurk\nGround Ghost");
    else if(n==624) printf("Pawniard\nDark Steel");
    else if(n==625) printf("Bisharp\nDark Steel");
    else if(n==626) printf("Bouffalant\nNormal");
    else if(n==627) printf("Rufflet\nNormal Flying");
    else if(n==628) printf("Braviary\nNormal Flying");
    else if(n==629) printf("Vullaby\nDark Flying");
    else if(n==630) printf("Mandibuzz\nDark Flying");
    else if(n==631) printf("Heatmor\nFire");
    else if(n==632) printf("Durant\nBug Steel");
    else if(n==633) printf("Deino\nDark Dragon");
    else if(n==634) printf("Zweilous\nDark Dragon");
    else if(n==635) printf("Hydreigon\nDark Dragon");
    else if(n==636) printf("Larvesta\nBug Fire");
    else if(n==637) printf("Volcarona\nBug Fire");
    else if(n==638) printf("Cobalion\nSteel Fighting");
    else if(n==639) printf("Terrakion\nRock Fighting");
    else if(n==640) printf("Virizion\nGrass Fighting");
    else if(n==641) printf("Tornadus\nFlying");
    else if(n==642) printf("Thundurus\nElectric Flying");
    else if(n==643) printf("Reshiram\nDragon Fire");
    else if(n==644) printf("Zekrom\nDragon Electric");
    else if(n==645) printf("Landorus\nGround Flying");
    else if(n==646) printf("Kyurem\nDragon Ice");
    else if(n==647) printf("Keldeo\nWater Fighting");
    else if(n==648) printf("Meloetta\nNormal Psychic");
    else if(n==649) printf("Genesect\nBug Steel");
    else if(n==650) printf("Chespin\nGrass");
    else if(n==651) printf("Quilladin\nGrass");
    else if(n==652) printf("Chesnaught\nGrass Fighting");
    else if(n==653) printf("Fennekin\nFire");
    else if(n==654) printf("Braixen\nFire");
    else if(n==655) printf("Delphox\nFire Psychic");
    else if(n==656) printf("Froakie\nWater");
    else if(n==657) printf("Frogadier\nWater");
    else if(n==658) printf("Greninja\nWater Dark");
    else if(n==659) printf("Bunnelby\nNormal");
    else if(n==660) printf("Diggersby\nNormal Ground");
    else if(n==661) printf("Fletchling\nNormal Flying");
    else if(n==662) printf("Fletchinder\nFire Flying");
    else if(n==663) printf("Talonflame\nFire Flying");
    else if(n==664) printf("Scatterbug\nBug");
    else if(n==665) printf("Spewpa\nBug");
    else if(n==666) printf("Vivillon\nBug Flying");
    else if(n==667) printf("Litleo\nFire Normal");
    else if(n==668) printf("Pyroar\nFire Normal");
    else if(n==669) printf("Flabébé\nFairy");
    else if(n==670) printf("Floette\nFairy");
    else if(n==671) printf("Florges\nFairy");
    else if(n==672) printf("Skiddo\nGrass");
    else if(n==673) printf("Gogoat\nGrass");
    else if(n==674) printf("Pancham\nFighting");
    else if(n==675) printf("Pangoro\nFighting Dark");
    else if(n==676) printf("Furfrou\nNormal");
    else if(n==677) printf("Espurr\nPsychic");
    else if(n==678) printf("Meowstic\nPsychic");
    else if(n==679) printf("Honedge\nSteel Ghost");
    else if(n==680) printf("Doublade\nSteel Ghost");
    else if(n==681) printf("Aegislash\nSteel Ghost");
    else if(n==682) printf("Spritzee\nFairy");
    else if(n==683) printf("Aromatisse\nFairy");
    else if(n==684) printf("Swirlix\nFairy");
    else if(n==685) printf("Slurpuff\nFairy");
    else if(n==686) printf("Inkay\nDark Psychic");
    else if(n==687) printf("Malamar\nDark Psychic");
    else if(n==688) printf("Binacle\nRock Water");
    else if(n==689) printf("Barbaracle\nRock Water");
    else if(n==690) printf("Skrelp\nPoison Water");
    else if(n==691) printf("Dragalge\nPoison Dragon");
    else if(n==692) printf("Clauncher\nWater");
    else if(n==693) printf("Clawitzer\nWater");
    else if(n==694) printf("Helioptile\nElectric Normal");
    else if(n==695) printf("Heliolisk\nElectric Normal");
    else if(n==696) printf("Tyrunt\nRock Dragon");
    else if(n==697) printf("Tyrantrum\nRock Dragon");
    else if(n==698) printf("Amaura\nRock Ice");
    else if(n==699) printf("Aurorus\nRock Ice");
    else if(n==700) printf("Sylveon\nFairy");
    else if(n==701) printf("Hawlucha\nFighting Flying");
    else if(n==702) printf("Dedenne\nElectric Fairy");
    else if(n==703) printf("Carbink\nRock Fairy");
    else if(n==704) printf("Goomy\nDragon");
    else if(n==705) printf("Sliggoo\nDragon");
    else if(n==706) printf("Goodra\nDragon");
    else if(n==707) printf("Klefki\nSteel Fairy");
    else if(n==708) printf("Phantump\nGhost Grass");
    else if(n==709) printf("Trevenant\nGhost Grass");
    else if(n==710) printf("Pumpkaboo\nGhost Grass");
    else if(n==711) printf("Gourgeist\nGhost Grass");
    else if(n==712) printf("Bergmite\nIce");
    else if(n==713) printf("Avalugg\nIce");
    else if(n==714) printf("Noibat\nFlying Dragon");
    else if(n==715) printf("Noivern\nFlying Dragon");
    else if(n==716) printf("Xerneas\nFairy");
    else if(n==717) printf("Yveltal\nDark Flying");
    else if(n==718) printf("Zygarde\nDragon Ground");

    return 0;
}